### ISSUE TITLE
新增yaml文件报错文件类型错误

### ISSUE THREAD

**Issue by scorpiopio** [lykops/lykops#2]
点击新增yaml文件，内容如下：
名称：test.yml
内容：

```
 - hosts: all
   tasks:
   - name: ping hosts
      ping:
      remote_user : root
```
描述：test ping

报错如下：

Request Method: POST
Request URL: http://192.168.122.102/ansible/yaml/add
Exception Type: MultiValueDictKeyError
Exception Value: "'file_type'"

**Comment by lykops** [comment]
已修复，重新获取代码
git pull
